<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcH1WyC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcH1WyC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNcH1WyC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNcH1WyC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNcH1WyC\App_KernelDevDebugContainer([
    'container.build_hash' => 'NcH1WyC',
    'container.build_id' => '2f820d9c',
    'container.build_time' => 1693337965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcH1WyC');
