<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIRsPSnh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIRsPSnh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIRsPSnh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIRsPSnh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIRsPSnh\App_KernelDevDebugContainer([
    'container.build_hash' => 'IRsPSnh',
    'container.build_id' => 'd4baa0f0',
    'container.build_time' => 1693321054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIRsPSnh');
