<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7C7YjLS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7C7YjLS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7C7YjLS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7C7YjLS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7C7YjLS\App_KernelDevDebugContainer([
    'container.build_hash' => '7C7YjLS',
    'container.build_id' => '26d6b01e',
    'container.build_time' => 1693323457,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7C7YjLS');
